import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
import {resolve} from 'node:path';
import {startFixture,root} from './fixture.mjs';
const fixture=await startFixture();
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=','base64');
const reference={filename:'reference.png',subfolder:'imports',type:'promptstudio',width:64,height:64};
try {
 await fixture.context.route('**/js/prompt_studio.js',async route=>{const response=await route.fetch();await route.fulfill({response,body:await response.text()+'\nexport {updateComposeMode,refreshWorkflowControls,captureGenerationQueueSettings,queueGeneration,restoreChatState,reviseAndMaybeGenerate,createNewFromCurrentPrompt,undoPrompt,handleStudioTurn,queueBackgroundReroll,discussionIsStale,appendGenerationImages,generateDirectPrompt};'});});
 await fixture.context.route('**/scripts/api.js',async route=>{const response=await route.fetch();await route.fulfill({response,body:await response.text()+'\napi.queuePrompt=async(_,snapshot)=>{window.queuedSnapshots||=[];window.queuedSnapshots.push(structuredClone(snapshot));return {prompt_id:"ref-test-"+window.queuedSnapshots.length};};'});});
 await fixture.context.route('**/promptstudio/prompt-studio/import-image',route=>route.fulfill({json:{image:reference}}));
 await fixture.context.route('**/promptstudio/prompt-studio/image?*',route=>route.fulfill({contentType:'image/png',body:png}));
 const page=await fixture.newPage();
 async function activate(){await page.evaluate(async()=>{
  const m=await import('/extensions/ComfyUI_PromptStudio/js/prompt_studio.js');
  const {state}=await import('/extensions/ComfyUI_PromptStudio/js/prompt-studio/core/state.js');
  window.refTest={m,state};
  const chat=state.chats.find(c=>c.id===state.activeChatId);
  chat.initialized=true;chat.selectedSource={filename:'base.png',subfolder:'',type:'output',width:64,height:64};
  const snapshot={workflow:{nodes:[],links:[]},output:{'1':{class_type:'KCPP_PromptSlot',inputs:{prompt:'Edit'}},'2':{class_type:'KCPP_ChatImageInput',inputs:{image_ref:''}},'3':{class_type:'KCPP_ChatImageReference',inputs:{image_ref:''}},'4':{class_type:'Krea2EditModelPatch',inputs:{source_image:['2',0],source_image_b:['3',0]}},'5':{class_type:'SaveImage',inputs:{images:['4',0]}}}};
  const profile={id:'ref',path:'ref',name:'[PS] Reference Edit',kind:'edit',promptNodeId:'1',imageNodeId:'2',resultNodeIds:['5'],snapshot,loraNodes:[],modelNodes:[]};
  const plain=structuredClone(profile);plain.id='plain';plain.path='plain';plain.name='[PS] Plain Edit';delete plain.snapshot.output['3'];delete plain.snapshot.output['4'].inputs.source_image_b;
  state.workflowProfiles=[profile,plain,{...plain,id:'create',path:'create',name:'[PS] Create',kind:'create'}];
  state.workflowBusy=true; // Host workflow listing is outside this composer test.
  chat.editWorkflowId='ref';state.apiConnected=true;
  m.refreshWorkflowControls();
  document.querySelector('#promptstudio-edit-workflow').value='ref';
  document.querySelector('input[name="promptstudio-generation-action"][value="edit"]').checked=true;
  document.querySelector('#promptstudio-use-llm-amplification').checked=false;
  m.updateComposeMode();
 });}

 const grounding={observations:'The dress is emerald-green, sleeveless, with a square neckline.',resolved_instruction:'Replace her dress with an emerald-green sleeveless dress with a square neckline.',edit_instruction:'Replace the dress in image 1 with the emerald-green dress in image 2. Preserve her identity, pose, and background.',uncertainty:'',needs_clarification:false};
 const oldMain='A woman in a red dress beside a book.';
 const oldFinal='A woman in a red dress beside a book, soft daylight.';
 const newMain='A woman in an emerald-green sleeveless dress with a square neckline beside a book.';
 const newFinal=newMain.slice(0,-1)+', soft daylight.';
 let analysisCalls=0, revisionCalls=[], routeCalls=[];
 await page.route('**/promptstudio/prompt-studio/vision-capability',r=>r.fulfill({json:{available:true}}));
 await page.route('**/promptstudio/prompt-studio/route-turn',r=>{routeCalls.push(r.request().postDataJSON());return r.fulfill({json:{route:'mutate_now',confidence:1,resolved_instruction:'Replace her dress using the reference.'}});});
 await page.route('**/promptstudio/prompt-studio/ground-edit-reference',r=>{const p=r.request().postDataJSON();analysisCalls++;assert.equal(p.source_image.filename,'base.png');assert.equal(p.reference_image.filename,'reference.png');return r.fulfill({json:{grounding}});});
 await page.route('**/promptstudio/prompt-studio/revise',r=>{const p=r.request().postDataJSON();revisionCalls.push(p);assert.equal(p.reference_grounding.observations,grounding.observations);return r.fulfill({json:{prompt:p.mode==='revise_main'?newMain:newFinal}});});
 await activate();
 await page.evaluate(({oldMain,oldFinal,reference})=>{const {m,state}=window.refTest;const chat=state.chats.find(c=>c.id===state.activeChatId);Object.assign(chat,{mainPrompt:oldMain,finalPrompt:oldFinal,currentPrompt:oldFinal,renderedMainPrompt:oldMain,renderedFinalPrompt:oldFinal,mainPromptDirty:false,versions:[{mainPrompt:oldMain,finalPrompt:oldFinal}],versionIndex:0,editReferenceImage:reference});m.restoreChatState(chat);document.querySelector('#promptstudio-use-llm-amplification').checked=true;document.querySelector('#promptstudio-auto-generate').checked=false;document.querySelector('input[name="promptstudio-generation-action"][value="edit"]').checked=true;m.updateComposeMode();},{oldMain,oldFinal,reference});
 await page.locator('#promptstudio-revision').fill("Replace her dress");
 await page.evaluate(()=>window.refTest.m.handleStudioTurn());
 const saved=await page.evaluate(()=>{const {state}=window.refTest;return state.chats.find(c=>c.id===state.activeChatId);});
 assert.equal(saved.mainPrompt,newMain);assert.equal(saved.finalPrompt,newFinal);
 assert.equal(saved.pendingGeneration.executionPrompt,grounding.edit_instruction);
 assert.equal(saved.pendingGeneration.referenceGrounding.observations,grounding.observations);
 assert.equal(routeCalls[0].has_reference_image,true);
 assert.equal(routeCalls[0].has_edit_reference,true);
 assert.equal(analysisCalls,1);assert.equal(revisionCalls.length,2);
 assert.equal(revisionCalls[0].intent_user_text,"Replace her dress");
 // A prepared instruction cannot follow a changed base or reference silently.
 await page.evaluate(()=>{const {state}=window.refTest;state.chats.find(c=>c.id===state.activeChatId).selectedSource.filename='different-base.png';});
 await page.evaluate(()=>window.refTest.m.createNewFromCurrentPrompt({applyControls:false,generationAction:'edit'}));
 assert.equal(await page.evaluate(()=>window.queuedSnapshots?.length||0),0);
 await page.evaluate(()=>{const {state}=window.refTest;const chat=state.chats.find(c=>c.id===state.activeChatId);chat.selectedSource.filename='base.png';chat.editReferenceImage.filename='different-reference.png';});
 await page.evaluate(()=>window.refTest.m.createNewFromCurrentPrompt({applyControls:false,generationAction:'edit'}));
 assert.equal(await page.evaluate(()=>window.queuedSnapshots?.length||0),0);
 await page.evaluate(()=>{const {state}=window.refTest;state.chats.find(c=>c.id===state.activeChatId).editReferenceImage.filename='reference.png';});
 await page.evaluate(async()=>{await window.refTest.state.chatSaveChain;});
 await page.reload();await page.waitForFunction(()=>window.studioReady);await activate();
 await page.evaluate(()=>{document.querySelector('#promptstudio-use-llm-amplification').checked=true;window.refTest.m.updateComposeMode();});
 assert.equal(await page.evaluate(()=>window.refTest.state.chats.find(c=>c.id===window.refTest.state.activeChatId).pendingGeneration.referenceGrounding.observations),grounding.observations);
 await page.evaluate(()=>window.refTest.m.createNewFromCurrentPrompt({applyControls:false,generationAction:'edit'}));
 const edit=await page.evaluate(()=>window.queuedSnapshots.at(-1));
 assert.equal(edit.output['1'].inputs.prompt,grounding.edit_instruction);
 assert.deepEqual(JSON.parse(edit.output['3'].inputs.image_ref),reference);
 assert.equal(analysisCalls,1,'Reroll must not repeat image analysis');
 const record=await page.evaluate(()=>window.refTest.state.chats.find(c=>c.id===window.refTest.state.activeChatId).messages.findLast(m=>m.generationSnapshot));
 assert.equal(record.referenceGrounding.observations,grounding.observations);
 await page.evaluate(async()=>{const {state,m}=window.refTest;const chat=state.chats.find(c=>c.id===state.activeChatId);const record=chat.messages.findLast(m=>m.generationSnapshot);state.generationJobs.get(record.promptId).autoAdvanceSource=true;await m.appendGenerationImages(record.promptId,[{filename:'edited-result.png',subfolder:'',type:'output',width:64,height:64}]);});
 assert.equal(await page.evaluate(()=>window.refTest.state.chats.find(c=>c.id===window.refTest.state.activeChatId).selectedSource.filename),'edited-result.png');
 await page.evaluate(()=>window.refTest.m.queueBackgroundReroll('edit'));
 assert.equal(await page.evaluate(()=>JSON.parse(window.queuedSnapshots.at(-1).output['2'].inputs.image_ref).filename),'base.png');
 assert.equal(await page.evaluate(()=>window.queuedSnapshots.at(-1).output['1'].inputs.prompt),grounding.edit_instruction);
 assert.equal(analysisCalls,1,'Reroll reuses the captured observations');
 await page.getByRole('button',{name:'Remove edit reference image'}).click();
 assert.equal(await page.locator('#promptstudio-current-prompt').inputValue(),newFinal);
 await page.evaluate(()=>{document.querySelector('input[name="promptstudio-generation-action"][value="create"]').checked=true;document.querySelector('#promptstudio-create-workflow').value='create';window.refTest.m.updateComposeMode();});
 await page.evaluate(()=>window.refTest.m.createNewFromCurrentPrompt({applyControls:false,generationAction:'create'}));
 const create=await page.evaluate(()=>window.queuedSnapshots.at(-1));
 assert.equal(create.output['1'].inputs.prompt,newFinal);assert.equal(create.output['3'],undefined);
 await page.evaluate(()=>window.refTest.m.undoPrompt());
 assert.equal(await page.locator('#promptstudio-current-prompt').inputValue(),oldFinal);
 assert.equal(await page.evaluate(()=>window.refTest.state.mainPrompt),oldMain);
 await page.route('**/promptstudio/prompt-studio/vision-capability',r=>r.fulfill({json:{available:false,reason:'Vision unavailable'}}));
 await page.evaluate(reference=>{const {state,m}=window.refTest;state.chats.find(c=>c.id===state.activeChatId).editReferenceImage=reference;document.querySelector('input[name="promptstudio-generation-action"][value="edit"]').checked=true;document.querySelector('#promptstudio-auto-generate').checked=false;m.updateComposeMode();},reference);
 await page.locator('#promptstudio-revision').fill('Use that dress');
 await page.evaluate(()=>window.refTest.m.reviseAndMaybeGenerate());
 assert.equal(await page.evaluate(()=>window.refTest.state.mainPrompt),oldMain);
 assert.equal(await page.locator('#promptstudio-current-prompt').inputValue(),oldFinal);
 assert.equal(analysisCalls,1);
 // Discussion receives the selected base plus the visible reference, in that order.
 await page.route('**/promptstudio/prompt-studio/vision-capability',r=>r.fulfill({json:{available:true}}));
 await page.route('**/promptstudio/prompt-studio/route-turn',r=>r.fulfill({json:{route:'discuss',confidence:1}}));
 let discussionPayload;
 await page.route('**/promptstudio/prompt-studio/discuss',r=>{discussionPayload=r.request().postDataJSON();return r.fulfill({json:{message:'The green mug can sit beside the blue one.',proposal:null}});});
 await page.locator('#promptstudio-revision').fill('Would this mug work beside the blue one?');
 await page.evaluate(()=>window.refTest.m.handleStudioTurn());
 const context=discussionPayload.messages.at(-1);
 assert.equal(context.images[0].filename,'base.png');assert.equal(context.images[1].filename,'reference.png');
 assert.deepEqual(context.context.attached_images.map(i=>i.label),['Image 1','Image 2']);
 assert.equal(await page.evaluate(()=>{const {state,m}=window.refTest;const chat=state.chats.find(c=>c.id===state.activeChatId);chat.editReferenceImage.filename='new-reference.png';return m.discussionIsStale(chat,chat.studioDiscussion);}),true);
 // A real clarification turn persists its bound request and accepts a short answer after reload.
 await page.evaluate(()=>{const {state,m}=window.refTest;state.chats.find(c=>c.id===state.activeChatId).editReferenceImage.filename='reference.png';m.updateComposeMode();});
 await page.route('**/promptstudio/prompt-studio/route-turn',r=>{routeCalls.push(r.request().postDataJSON());return r.fulfill({json:{route:'mutate_now',confidence:1,resolved_instruction:'Replace her dress using the selected reference dress.'}});});
 let clarificationRequests=[];
 await page.route('**/promptstudio/prompt-studio/ground-edit-reference',r=>{clarificationRequests.push(r.request().postDataJSON());return r.fulfill({json:{grounding:clarificationRequests.length===1?{...grounding,needs_clarification:true,uncertainty:'Which dress should I use?'}:grounding}});});
 await page.locator('#promptstudio-revision').fill('Replace her dress');
 await page.evaluate(()=>window.refTest.m.handleStudioTurn());
 assert.equal(await page.locator('#promptstudio-revision').inputValue(),'');
 assert.equal(await page.evaluate(()=>window.refTest.state.chats.find(c=>c.id===window.refTest.state.activeChatId).referenceClarification.question),'Which dress should I use?');
 await page.evaluate(async()=>{await window.refTest.state.chatSaveChain;});
 await page.reload();await page.waitForFunction(()=>window.studioReady);await activate();
 await page.evaluate(()=>{document.querySelector('#promptstudio-use-llm-amplification').checked=true;document.querySelector('#promptstudio-auto-generate').checked=false;window.refTest.m.updateComposeMode();});
 await page.locator('#promptstudio-revision').fill('The green one.');
 await page.evaluate(()=>window.refTest.m.handleStudioTurn());
 assert.equal(routeCalls.at(-1).discussion_history[0].text,'Replace her dress');
 assert.equal(routeCalls.at(-1).discussion_history[1].text,'Which dress should I use?');
 assert.ok(clarificationRequests.at(-1).user_text.includes('Replace her dress'));
 assert.ok(clarificationRequests.at(-1).user_text.includes('The green one.'));
 assert.equal(clarificationRequests.at(-1).clarification_question,'Which dress should I use?');
 assert.ok(!clarificationRequests.at(-1).user_text.includes('Which dress should I use?'));
 assert.equal(await page.evaluate(()=>window.refTest.state.chats.find(c=>c.id===window.refTest.state.activeChatId).referenceClarification),null);
 // Cancel clears an outstanding clarification rather than carrying it into a later request.
 await page.evaluate(()=>{const {state,m}=window.refTest;const chat=state.chats.find(c=>c.id===state.activeChatId);chat.referenceClarification={...m.captureGenerationQueueSettings('edit',chat),userText:'Use this dress',question:'Which dress?',mainPrompt:chat.mainPrompt,finalPrompt:chat.finalPrompt};});
 await page.route('**/promptstudio/prompt-studio/route-turn',r=>r.fulfill({json:{route:'cancel_pending',confidence:1}}));
 await page.locator('#promptstudio-revision').fill('Never mind');
 await page.evaluate(()=>window.refTest.m.handleStudioTurn());
 assert.equal(await page.evaluate(()=>window.refTest.state.chats.find(c=>c.id===window.refTest.state.activeChatId).referenceClarification),null);
 await page.route('**/promptstudio/prompt-studio/route-turn',r=>r.fulfill({json:{route:'mutate_now',confidence:1,resolved_instruction:'Match this dress'}}));
 // No-op results may synchronize scene text, but must not auto-generate unrelated changes.
 await page.route('**/promptstudio/prompt-studio/ground-edit-reference',r=>r.fulfill({json:{grounding:{...grounding,already_satisfied:true}}}));
 await page.evaluate(()=>{document.querySelector('#promptstudio-auto-generate').checked=true;});
 const beforeNoop=await page.evaluate(()=>window.queuedSnapshots?.length||0);
 await page.locator('#promptstudio-revision').fill('Match this dress');
 await page.evaluate(()=>window.refTest.m.handleStudioTurn());
 assert.equal(await page.evaluate(()=>window.queuedSnapshots?.length||0),beforeNoop);
 assert.equal(await page.evaluate(()=>window.refTest.state.chats.find(c=>c.id===window.refTest.state.activeChatId).pendingGeneration.referenceGrounding.already_satisfied),true);
 // Failure of Final after successful Main preparation leaves the entire stored pair intact.
 await page.route('**/promptstudio/prompt-studio/ground-edit-reference',r=>r.fulfill({json:{grounding}}));
 await page.route('**/promptstudio/prompt-studio/revise',r=>r.request().postDataJSON().mode==='revise_main'?r.fulfill({json:{prompt:'A completely changed staged Main.'}}):r.fulfill({status:400,json:{error:'Requested placement was not preserved.'}}));
 const beforeFailure=await page.evaluate(()=>({main:window.refTest.state.mainPrompt,final:window.refTest.state.currentPrompt}));
 await page.locator('#promptstudio-revision').fill('Place this beside the original');
 await page.evaluate(()=>window.refTest.m.handleStudioTurn());
 assert.deepEqual(await page.evaluate(()=>({main:window.refTest.state.mainPrompt,final:window.refTest.state.currentPrompt})),beforeFailure);
 assert.equal(await page.evaluate(()=>window.queuedSnapshots?.length||0),beforeNoop);
 // Direct reference instructions must not overwrite scene prompts or leak when switching to Create.
 await page.evaluate(()=>{document.querySelector('#promptstudio-use-llm-amplification').checked=false;window.refTest.m.updateComposeMode();});
 await page.locator('#promptstudio-revision').fill('Place this mug next to the original');
 assert.deepEqual(await page.evaluate(()=>({main:window.refTest.state.mainPrompt,final:window.refTest.state.currentPrompt})),beforeFailure,'Typing a direct instruction keeps the scene intact');
 await page.evaluate(()=>window.refTest.m.generateDirectPrompt('edit'));
 assert.deepEqual(await page.evaluate(()=>({main:window.refTest.state.mainPrompt,final:window.refTest.state.currentPrompt})),beforeFailure);
 assert.equal(await page.evaluate(()=>window.queuedSnapshots.at(-1).output['1'].inputs.prompt),'Place this mug next to the original');
 await page.locator('label:has(input[name="promptstudio-generation-action"][value="create"])').click();
 assert.equal(await page.locator('#promptstudio-revision').inputValue(),beforeFailure.final);
 assert.deepEqual(fixture.errors,[]);
 console.log('Grounded edit: router reference context, shared analysis, Main/Final, edit instruction, durable history, Create switch, Undo and vision failure passed.');
} finally {await fixture.close();}
