import assert from 'node:assert/strict';
import {resolve} from 'node:path';
import {startFixture, attachVideo, root, videoEnabled} from './fixture.mjs';
if (!videoEnabled) process.exit(0);
const fixture=await startFixture();
try {
  await fixture.context.route('**/js/promptstudio_video_studio.js',async route=>{
    const response=await route.fetch();await route.fulfill({response,body:await response.text()+'\nwindow.timelineTest={state,activeProject,renderAll,renderTimeline,openShotEditor,persistProjects,markProjectChanged};'});
  });
  const page=await fixture.newPage();await attachVideo(page);await page.locator('#psvstudio-new-project').click();
  const seed=async()=>page.evaluate(()=>{
    const {activeProject,renderAll,state}=window.timelineTest,p=activeProject();
    const shot=structuredClone(p.document.shots[0]);shot.id='a';shot.start=0;
    shot.steps=[{id:'action',type:'action',text:'First action',start:0,end:.75,timing_explicit:true},{id:'overlap',type:'action',text:'Overlapping action',start:.25,end:.9,timing_explicit:true}];
    p.document.duration_seconds=5;p.document.shots=[shot,{...structuredClone(shot),id:'b',start:1,steps:[]}];
    p.document.references=[];state.selectedShotId='a';renderAll();
  });
  await seed();
  const toolbar=page.locator('#psvstudio-timing-toolbar');
  await toolbar.getByLabel('Display',{exact:true}).selectOption('frames');
  assert.match(await toolbar.innerText(),/124 frames/);
  const end=toolbar.getByRole('textbox',{name:'Selected shot end',exact:true});
  await end.fill('12');await end.press('Tab');
  assert.equal(await page.evaluate(()=>window.timelineTest.activeProject().document.shots[1].start),1);
  await toolbar.getByLabel('Events when shortening',{exact:true}).selectOption('scale');
  await end.fill('12');await end.press('Tab');
  assert.equal(await page.evaluate(()=>window.timelineTest.activeProject().document.shots[1].start),.5);
  await toolbar.getByRole('button',{name:'Undo',exact:true}).click();
  assert.equal(await page.evaluate(()=>window.timelineTest.activeProject().document.shots[1].start),1);
  await toolbar.getByRole('button',{name:'Redo',exact:true}).click();
  assert.equal(await page.evaluate(()=>window.timelineTest.activeProject().document.shots[1].start),.5);
  await seed();
  const handle=page.locator('.psvstudio-shot-block').first().locator('.psvstudio-trim-right');
  await handle.press('ArrowRight');await handle.press('ArrowRight');await handle.press('ArrowLeft');
  assert.equal(await page.evaluate(()=>window.timelineTest.activeProject().document.shots[1].start),25/24);
  const before=await page.evaluate(()=>JSON.stringify(window.timelineTest.activeProject().document));
  const box=await handle.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+80,box.y,{steps:5});
  assert.equal(await page.evaluate(()=>JSON.stringify(window.timelineTest.activeProject().document)),before, 'Dragging must not expose uncommitted edits to autosave');
  await page.keyboard.press('Escape');await page.mouse.up();
  assert.equal(await page.evaluate(()=>JSON.stringify(window.timelineTest.activeProject().document)),before);
  await page.evaluate(()=>window.timelineTest.openShotEditor('a'));
  const dialog=page.getByRole('dialog',{name:'Edit Shot 1',exact:true});
  const blocks=dialog.locator('.psvstudio-shot-cue.is-action');
  const boxes=await blocks.evaluateAll(nodes=>nodes.map(node=>node.getBoundingClientRect().top));assert.notEqual(boxes[0],boxes[1]);
  await blocks.first().press('ArrowRight');
  assert.equal(await page.evaluate(()=>window.timelineTest.state.shotEditorDraft.steps[0].start),1/24);
  await dialog.getByRole('button',{name:'Undo',exact:true}).click();
  assert.equal(await page.evaluate(()=>window.timelineTest.state.shotEditorDraft.steps[0].start),0);
  await dialog.getByRole('button',{name:'+1 frame',exact:true}).click();
  assert.equal(await dialog.getByRole('textbox',{name:'Shot playhead',exact:true}).inputValue(),'1');
  await dialog.getByLabel('Shot zoom',{exact:true}).selectOption('4');
  assert.equal(await dialog.locator('.psvstudio-shot-timeline-scroll').evaluate(node=>node.scrollWidth>node.clientWidth),true);
  await page.screenshot({path:resolve(root,'test-results/browser/video-timeline-shot.png')});
  await page.evaluate(()=>{ window.timelineTest.activeProject().document.shots[0].notes = 'Concurrent newer edit'; });
  await dialog.getByRole('button',{name:'Save shot',exact:true}).click();
  assert.equal(await dialog.isVisible(),true);
  assert.equal(await page.evaluate(()=>window.timelineTest.activeProject().document.shots[0].notes),'Concurrent newer edit');
  await page.evaluate(()=>{window.timelineTest.activeProject().document.shots[0].notes = window.timelineTest.state.shotEditorOriginal.notes;});
  await dialog.getByRole('button',{name:'Save shot',exact:true}).click();
  await page.evaluate(()=>{
    const p=window.timelineTest.activeProject();
    p.document.references=[{id:'guide',kind:'video',path:'guide.mp4',name:'Motion',roles:['timeline_guide'],guide_frame:72,trim_start:0,trim_end:1,duration_seconds:1}];
    window.timelineTest.markProjectChanged();window.timelineTest.renderAll();
  });
  const guide=page.locator('[data-guide-id="guide"]');assert.match(await guide.getAttribute('title'),/72–94/);
  await guide.press('Shift+ArrowRight');assert.equal(await page.evaluate(()=>window.timelineTest.activeProject().document.references[0].guide_frame),96);
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.screenshot({path:resolve(root,'test-results/browser/video-timeline-narrow.png')});
  await page.evaluate(()=>window.timelineTest.persistProjects({immediate:true}));
  await page.reload();await page.waitForFunction(()=>window.studioReady);await attachVideo(page);
  assert.equal(await page.evaluate(()=>window.timelineTest.activeProject().document.references[0].guide_frame),96);
  assert.equal(await page.evaluate(()=>window.timelineTest.activeProject().document.shots[1].start),25/24);
  assert.deepEqual(fixture.errors,[]);
  console.log('Timeline frame edits, preserve/scale, undo/redo, cancel, overlapping cues, transport, zoom, guides, narrow layout and persistence passed.');
} finally {await fixture.close();}
