function createInitialState() {
  return {
    panel: null,
    launcher: null,
    popup: null,
    popupCloseTimer: null,
    dockingPopup: false,
    returnToEmbedded: false,
    standaloneChannel: null,
    videoStudioChannel: null,
    videoStudioPresence: new Map(),
    videoStudioServerPresence: new Map(),
    videoStudioPresenceTimer: null,
    videoStudioInstalled: null,
    videoStudioCapabilityRequest: null,
    videoHandoffRequests: new Map(),
    workflowSyncChannel: null,
    chatSyncChannel: null,
    config: null,
    mutationConfig: null,
    mutationConfigPending: null,
    mutationConfigLoading: false,
    mutationConfigTimer: null,
    mutationManagerCategory: "",
    mutationEditorIndex: null,
    mutationEditorDirty: false,
    mutationDeleteIndex: null,
    mutationManagerTrigger: null,
    llmProfiles: [],
    llamacppConfigLlmProfiles: new Map(),
    llmProfileEditorTrigger: null,
    llmProfileEditorId: null,
    mainPrompt: "",
    currentPrompt: "",
    versions: [],
    versionIndex: -1,
    busy: false,
    generating: false,
    queueing: false,
    operationToken: 0,
    pollToken: 0,
    activeGenerationPromptId: "",
    consultGenerationTarget: null,
    consultAgentGenerationTarget: null,
    consultAgentRunning: false,
    consultAgentRunToken: 0,
    consultAgentAbortController: null,
    consultAgentRequestId: "",
    generationProgress: new Map(),
    generationJobs: new Map(),
    consultGenerationJobs: new Map(),
    operationControllers: new Map(),
    generationFailures: new Map(),
    historyScrollRevision: 0,
    consultHistoryScrollRevision: 0,
    historyWasNearEnd: true,
    consultHistoryWasNearEnd: true,
    promptWorkerSeenAlive: false,
    promptWorkerHealthCheckedAt: 0,
    promptWorkerHealthRequest: null,
    studioPreparations: new Map(),
    latestStudioPreparationByChat: new Map(),
    studioTurnBusyChatIds: new Set(),
    chats: [],
    activeChatId: null,
    chatRevision: 0,
    chatPageOffset: 0,
    chatPageCursor: null,
    chatTotal: 0,
    chatHasMore: false,
    chatPageLoading: false,
    chatDeletedIds: new Set(),
    chatStoreLoaded: false,
    chatPersistenceBlocked: false,
    chatSaveInFlight: false,
    chatMutationVersion: 0,
    chatSyncInFlight: false,
    chatSyncTimer: null,
    consultBusy: false,
    consultPendingText: "",
    consultJobs: new Map(),
    llmStatusRequest: null,
    llmStatusRequestProvider: "",
    llmStatusTimer: null,
    llmStatusSnapshot: null,
    comfyQueueRemaining: 0,
    comfyRestartBusy: false,
    comfyUpdateBusy: false,
    comfyUpdateError: false,
    comfyUpdateMessage: "",
    comfyUpdateNeedsRestart: false,
    comfyUpdateDoneCount: 0,
    comfyUpdateTotalCount: 0,
    comfyUpdateRequestId: "",
    comfyUpdateResults: new Map(),
    koboldAbortBusy: false,
    llamacppProcessBusy: false,
    llamacppAutostartBusy: false,
    llamacppAutostartEnabled: false,
    consultVisionAvailable: null,
    consultVisionReason: "",
    consultSelectedImages: new Map(),
    consultImageChoices: new Map(),
    consultUploadedImages: [],
    mainPastedImage: null,
    mainPastedImagesByChat: new Map(),
    workflowProfiles: [],
    workflowIssues: [],
    workflowRevision: 0,
    workflowStoreLoaded: false,
    workflowSaveChain: Promise.resolve(),
    workflowBusy: false,
    workflowRefreshTimer: null,
    workflowRefreshBroadcast: false,
    plotRuns: new Map(),
    plotLoads: new Map(),
    plotSaveChains: new Map(),
    plotWatchers: new Map(),
    plotSubmitting: new Set(),
    plotPreparationControllers: new Map(),
    plotCompositeBuilding: new Set(),
    plotErrors: new Map(),
    plotActiveZ: new Map(),
    plotCatalogs: new Map(),
    plotCellSize: 220,
    loraSelections: {},
    loraCatalogs: new Map(),
    loraRenderToken: 0,
    modelSelections: {},
    modelCatalogs: new Map(),
    modelRenderToken: 0,
    chatSaveTimer: null,
    chatSaveChain: Promise.resolve(),
    lightboxTrigger: null,
    generationRetry: null,
    generationFailureTrigger: null,
    dragDepth: 0,
    activityIndicatorDocument: null,
    activityIndicatorVisible: false,
    activityOriginalTitle: "",
    activityOriginalFavicon: null,
    activityOriginalFaviconHref: null,
    activityOriginalFaviconType: null,
    activityCreatedFavicon: false,
    apiConnected: true,
    disconnectedGenerationTimer: null,
    disconnectedControls: new Map(),
    disconnectedControlObserver: null,
  };
}

export const state = createInitialState();
