name: Publish to Comfy registry
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "pyproject.toml"

jobs:
  quality:
    uses: ./.github/workflows/quality.yml
  publish-node:
    needs: quality
    name: Publish Custom Node to registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Publish Custom Node
        uses: Comfy-Org/publish-node-action@d2366e7abb6ab16f3bb03e3520ae25c8cf749bc9
        with:
          personal_access_token: ${{ secrets.REGISTRY_ACCESS_TOKEN }} ## Add your own personal access token to your Github Repository secrets and reference it here.
